
""" ToDos """
TODOS_TITLE_MAX_LEN = 64
TODOS_DESC_MAX_LEN = 256
TODOS_PRIORITY_MIN = 1
TODOS_PRIORITY_MAX = 4
TODOS_COMPLETED_DEFAULT = False


""" Users """
USERS_USERNAME_MAX_LEN = 32
USERS_PASSWORD_MIN_LEN = 16
USERS_PASSWORD_MAX_LEN = 32
USERS_EMAIL_MAX_LEN = 128
USERS_FIRSTNAME_MAX_LEN = 64
USERS_LASTNAME_MAX_LEN = 64


""" Auth """
